const ADD_COURSE = "ADD_COURSE";
const ADD = "ADD";
const CREATE_POST = "POST/CREATE_POST";
const FETCH_POSTS = "POST/FETCH_POSTS";
const SHOW_LOADER = "APP/SHOW_LOADER";
const HIDE_LOADER = "APP/HIDE_LOADER";

export { ADD, ADD_COURSE, CREATE_POST, FETCH_POSTS };
