const ADD_COURSE = "ADD_COURSE";
const ADD = "ADD";
const CREATE_POST = "POST/CREATE_POST";
const FETCH_POSTS = "POST/FETCH_POSTS";
const SHOW_LOADER = "APP/SHOW_LOADER";
const HIDE_LOADER = "APP/HIDE_LOADER";
const SHOW_ALERT = "SHOW_ALERT";
const HIDE_ALERT = "HIDE_ALERT";

export {
  ADD,
  ADD_COURSE,
  CREATE_POST,
  FETCH_POSTS,
  SHOW_LOADER,
  HIDE_LOADER,
  SHOW_ALERT,
  HIDE_ALERT
};
